spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  liquibase:
    change-log: db.changelog/changelog.xml
  jpa:
    open-in-view: false

accounting-service:
  url: ${ACCOUNTING_SERVICE_URL}

security-service:
  url: ${SECURITY_SERVICE_URL}



