server:
  port: ${SERVER_PORT:0}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/resignation-db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:1234}
  
  liquibase:
    change-log: db.changelog/changelog.xml
  
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  
  main:
    banner-mode: off

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - circuitbreakers
          - circuitbreakerevents
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    configs:
      default:
        failureRateThreshold: 50
        sliding-window-type: COUNT_BASED
        sliding-window-size: 2
        minimum-number-of-calls: 1
        failure-rate-threshold: 50
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - feign.FeignException.InternalServerError
          - feign.FeignException.ServiceUnavailable
          - feign.FeignException.GatewayTimeout
          - feign.RetryableException
        ignore-exceptions:
          - feign.FeignException.BadRequest
          - feign.FeignException.Unauthorized
          - feign.FeignException.Forbidden
          - feign.FeignException.NotFound
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
    instances:
      accounting:
        base-config: default
      security:
        base-config: default
  
  
  retry:
    retry-aspect-order: 2
    configs:
      default:
        maxAttempts: 3
        waitDuration: 5000ms
        retry-exceptions:
          - feign.RetryableException
          - java.net.SocketTimeoutException
          - java.io.IOException
        ignore-exceptions:
          - feign.FeignException.BadRequest
          - feign.FeignException.Unauthorized
          - feign.FeignException.Forbidden
          - feign.FeignException.NotFound
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
    instances:
      accounting:
        base-config: default
      security:
        base-config: default



